# Generated by Django 3.2.12 on 2022-05-23 02:34

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3),
        ),
    ]
