# Generated by Django 3.2.12 on 2022-05-25 01:47

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0.00'), default_currency='USD', max_digits=14, null=True),
        ),
    ]
